#!/bin/bash

START="$(date +%s.%N)"


input_code=$1
input_info=$2
#output should have path to correct place in dryvr directory
output=$3

GSTART="$(date +%s.%N)"

python generateGraph-new.py $input_code $input_info $output

GEND="$(date +%s.%N)"

python main.py $output

END="$(date +%s.%N)"
#DURATION=$[ $'expr (date +%s.%N) - ${START}' ]
DURATION=$( echo "$END - $START" | bc -l  )
GDURATION=$( echo "$GEND - $GSTART" | bc -l  )

echo "Running time of pipeline is"
echo ${DURATION}
echo "Running time of model generation is"
echo ${GDURATION}
